package EjerciciosCollecciones;

public enum Nombres {
    SUSY_PRIMARIA, SUSY_SECUNDARIA, SUSY_PRAPARATORIA, SUSY_UNIVERSIDAD,
    GIL_PRIMARIA, GIL_SECUNDARIA, GIL_PRAPARATORIA, GIL_UNIVERSIDAD,
    JUDY_PRIMARIA,JUDY_SECUNDARIA, JUDY_PRAPARATORIA, JUDY_UNIVERSIDAD,
}